let maps = [
    [{
        "x": 120,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 40,
        "name": "block3",
        "hp": 3
    }],
    [{
        "x": 40,
        "y": 40,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 60,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 80,
        "name": "block2",
        "hp": 2
    }, {
        "x": 80,
        "y": 40,
        "name": "block2",
        "hp": 2
    }, {
        "x": 80,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 40,
        "name": "block2",
        "hp": 2
    }, {
        "x": 120,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 40,
        "name": "block2",
        "hp": 2
    }, {
        "x": 160,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 40,
        "name": "block2",
        "hp": 2
    }, {
        "x": 200,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 40,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 60,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 80,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 100,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 120,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 140,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 160,
        "name": "block2",
        "hp": 2
    }, {
        "x": 40,
        "y": 180,
        "name": "block2",
        "hp": 2
    }, {
        "x": 80,
        "y": 100,
        "name": "block2",
        "hp": 2
    }, {
        "x": 80,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 180,
        "name": "block2",
        "hp": 2
    }, {
        "x": 120,
        "y": 100,
        "name": "block2",
        "hp": 2
    }, {
        "x": 120,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 180,
        "name": "block2",
        "hp": 2
    }, {
        "x": 160,
        "y": 100,
        "name": "block2",
        "hp": 2
    }, {
        "x": 160,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block2",
        "hp": 2
    }, {
        "x": 200,
        "y": 100,
        "name": "block2",
        "hp": 2
    }, {
        "x": 200,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 100,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 120,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 140,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 160,
        "name": "block2",
        "hp": 2
    }, {
        "x": 240,
        "y": 180,
        "name": "block2",
        "hp": 2
    }],
    [{
        "x": 80,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 120,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 160,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 280,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 280,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 280,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 280,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 280,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 280,
        "y": 180,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 120,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 80,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 40,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 40,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 40,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 80,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 0,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 0,
        "y": 120,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 160,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 240,
        "y": 180,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 120,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 20,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 160,
        "name": "block1",
        "hp": 1
    }],
    [{
        "x": 120,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 40,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 60,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 80,
        "name": "block1",
        "hp": 1
    }, {
        "x": 120,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 100,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 120,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 140,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 160,
        "name": "block1",
        "hp": 1
    }, {
        "x": 160,
        "y": 180,
        "name": "block1",
        "hp": 1
    }, {
        "x": 200,
        "y": 180,
        "name": "block1",
        "hp": 1
    }]
]